# Generated by Django 5.0.6 on 2024-06-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_intro_sub_title_alter_story_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='sub_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='sub_title',
            field=models.TextField(),
        ),
    ]
